name: HodgeNet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cudatoolkit=11.1.1
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - igl=2.2.1
  - intel-openmp=2021.3.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuv=1.42.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pillow=8.3.1
  - pip=21.1.3
  - python=3.9.6
  - python_abi=3.9
  - pytorch=1.9.0
  - readline=8.1
  - scipy=1.7.0
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - torchvision=0.10.0
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.13.0
    - cachetools==4.2.2
    - charset-normalizer==2.0.4
    - google-auth==1.34.0
    - google-auth-oauthlib==0.4.5
    - grpcio==1.39.0
    - idna==3.2
    - markdown==3.3.4
    - oauthlib==3.1.1
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tqdm==4.62.0
    - trimesh==3.9.25
    - urllib3==1.26.6
    - werkzeug==2.0.1
